server:
  port: '8080'

management:
  health:
    circuitbreakers:
      enabled: true
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
      path-mapping:
        prometheus: metrics
  # endpoint:
  #   metrics:
  #     enabled: true
  #   prometheus:
  #     enabled: true
  #   health:
  #     show-details: always
  
spring:
  cloud:
    consul:
      discovery:
        instanceId: ms-gateway
        health-check-interval: 5s
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ms-money
        uri: lb://ms-money
        predicates:
        - Path=/money/**
        filters:
        - RewritePath=/money/(?<segment>.*), /$\{segment}
        - name: CircuitBreaker
          args:
            name: monitor-money
            fallbackUri: forward:/fallback/money